//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSphereRemote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceRegistry
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public string DesiredProperties { get; set; }
        public string ReportedProperties { get; set; }
        public string ETags { get; set; }
        public string MethodName { get; set; }
        public string MethodPayload { get; set; }
        public string C2DMessage { get; set; }
    }
}
